### ISSUE TITLE
A special case

### ISSUE THREAD

**Issue by electrocnic** [cg-tuwien/TAA-STAR#4]
https://github.com/cg-tuwien/TAA-STAR/blob/0ec6a7c83765b7b1984ad18616c31f2409ace252/source/main.cpp#L2559

I have based our vertex-skinning code on this repo now (finally after 3 days of reading the whole main.cpp, I understood most parts of it so I could get a simple animated mesh rendered in my code).

However, the above lines needed to be with a divide (`/`) instead of multiply (`*`) in order to repeat the animation at the correct time values. Else my animation would wait up to around 900 seconds (because of 39 ticks multiplied by 24 ticks per second yields that amound). It should rather restart at the end of the time, so I figured out that it should be a division (in both lines).

However, I tested your TAA code with the provided goblin and it seems to work fine, both times with `*` AND with `/` so I am a bit confused right now. (Maybe your animation is so long that you would have to wait quite a while until the issue can be seen?)
(Maybe it is my own misconception somewhere?)

I was talking about `clip.mEndTicks / clip.mTicksPerSecond` instead of `clip.mEndTicks * clip.mTicksPerSecond` and the same for the line above.

Kind regards!

**Comment by alexc71** [comment]
Thanks a lot, this is indeed a bug. Good finding!
It just happened that all the animation models I testet with have `mTicksPerSecond == 1.0`, so the multiplication (or division) just do nothing on them.
I'll fix that ASAP.
