### ISSUE TITLE
Vertex skinning shader bug

### ISSUE THREAD

**Issue by electrocnic** [cg-tuwien/TAA-STAR#5]
https://github.com/cg-tuwien/TAA-STAR/blob/637921e206cf16f9de2c10ad3dda3716323b23f7/shaders/animatedObject.vert#L63

These two lines of code introduced weird artifacts in my models (which I made myself in Blender) as you can see here:
https://youtu.be/qLwsRKFF5B4

I could get rid of the artifacts by really normalizing the weights and clamping them between 0 and 1:
```
vec4 boneWeights = max(min(normalize(aBoneWeights), 1.0), 0.0);
boneWeights.w = min(max(1.0 - boneWeights.x - boneWeights.y - boneWeights.z, 0.0), 1.0);
```
... as you can see here: https://youtu.be/EzbR53n_wyA

Not clamping between 0 and 1 (e.g. only clamping 0) is not enough, as one additional model of mine showed. Really go for 0 and 1.

Best regards!

**Comment by alexc71** [comment]
Hmm, that is strange.
While the modifications won't hurt, their necessity implies that your `aBoneWeights` either add up to more than 1.0 (which would be quite unexpected), or that there are negative weights... (or that I'm overlooking something).
Will have to investigate that issue a bit.
